---
- name: update web and nfs servers
  hosts: webservers, nfs
  become: yes

  tasks:
    - name: Install wireshark on RedHat/Amazon Linux
      yum:
        name: wireshark
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install wireshark on Debian/Ubuntu
      apt:
        name: wireshark
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

- name: update LB and DB server
  hosts: lb, db
  become: yes

  tasks:
    - name: Install wireshark on Debian/Ubuntu
      apt:
        name: wireshark
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install wireshark on RedHat/Amazon Linux
      yum:
        name: wireshark
        state: latest
      when: ansible_os_family == "RedHat"
