all:
  children:
    nfs:
      hosts:
        172.31.17.87:
          ansible_user: ec2-user

    webservers:
      hosts:
        172.31.20.245:
          ansible_user: ec2-user
        172.31.30.145:
          ansible_user: ec2-user
        172.31.28.24:
          ansible_user: ec2-user

    db:
      hosts:
        172.31.23.137:
          ansible_user: ec2-user

    lb:
      hosts:
        172.31.31.128:
          ansible_user: ubuntu